name: Copy src to docs

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy src to docs/src
        run: |
          mkdir -p docs/src
          cp -r src/* docs/src/

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/src
          git commit -m "Copy src to docs/src via GitHub Actions" || echo "No changes to commit"
          git push
